version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankingdb
    ports:
      - "5432:5432"
    networks:
      - basd

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - basd

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - basd
  people-api:
    build:
      context: ./Backend/People
      dockerfile: People.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=bankingdb;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - basd

  account-api:
    build:
      context: ./Backend/Account
      dockerfile: Account.API/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=bankingdb;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - basd

  transaction-api:
    build:
      context: ./Backend/Transaction
      dockerfile: Transaction.API/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=bankingdb;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - basd
  bff-api:
    build:
      context: ./Backend/BFF
      dockerfile: BFF.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PeopleApiUrl=http://people-api:80
      - AccountApiUrl=http://account-api:80
      - TransactionApiUrl=http://transaction-api:80
      - Redis__ConnectionString=redis:6379
    depends_on:
      - people-api
      - account-api
      - transaction-api
      - redis
    networks:
      - basd

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

networks:
  basd:
    driver: bridge
